### ISSUE TITLE
Plugin is not installed

### ISSUE THREAD

**Issue by tjapro** [rdilweb/mkdocs-plugin-progress#1]
After install this plugin, I receive this message:
```
.env ❯ mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'plugins'. Error: The "mkdocs-plugin-progress" plugin is not installed

Aborted with 1 Configuration Errors!
```

**Comment by RDIL** [comment]
Can I see your `mkdocs.yml` please?

**Comment by tjapro** [comment]
```
site_name: TP Docs
site_description: Tiago Programmer Documentation
site_author: Tiago Almeida <tjamadeira@gmail.com>

copyright: "Coded by <em>Tiago Programmer</em> with <em>love</em>. &copy; 2019"
repo_url: https://gitlab.com/tjapro/docs

theme:
  name: mkdocs
  hljs_style: atom-one-dark
  highlightjs: true
  shortcuts:
    help: 72 # h
    next: 78 # n
    previous: 80 # p
    search: 83 # s

# extra_css:
#   - assets/css/extra.css

markdown_extensions:
  - toc:
      permalink: "#"
  - sane_lists
  - nl2br # newline hard break

plugins:
  - search
  # - mkdocs-plugin-progress
  # - mkdocs-minify-plugin

nav:
  - Git: git.md
  - Versioning: semver.md
  - CSS:
      - eCSS: css/ecss.md
  - Python: python.md
  - About: about.md

```
